package me.jwkwon0817.tetrio.tetriobot.global.exceptions

class UserNotFoundException : RuntimeException("User not found!") 